### ISSUE TITLE
Location updating 

### ISSUE THREAD

**Issue by MK040NL** [Dielee/volvo2mqtt#101]
Because of an issue with my SD Card I had to reinstall my HomeAssistant. With my old install I was able to log my cars location. Esch 60seconds I received the location and could plot it on the HA map. Even while driving. 

However after the reinstall this part of the location logging is not working. I also installed the HomeAssistant app on my car (Volvo XC40 BEV 2023). 

Anyone a tip on solving it?

**Comment by steynovich** [comment]
AFAIK is live location via Volvo On Call disabled (privacy concerns) while driving and is the location only updated once the car is switched off.

I've noticed today that the location of my car isn't updated at all. Has nothing to do with this integration, because the official Volvo-app is also showing this same behavior. Probably a glitch in the Volvo API.

**Comment by MK040NL** [comment]
Thanks for the reply. I found a solution for my issue. I have the HomeAssistant app installed on Android Auto but after the crash of my HA install on my raspberry I didn't do a reset of the car app. So today I deleted the HA app en reinstall it. Added a device-tracker to this device and now it is updating while driving!!



[image](https://github.com/Dielee/volvo2mqtt/assets/138472007/39ac37b1-3337-4158-ba58-cb307c8e47c3)
