### ISSUE TITLE
HA App stopped updating after new Volvo app update

### ISSUE THREAD

**Issue by amurray81** [Dielee/volvo2mqtt#119]
Hi 

Sometime in the past 2 days the android app was updated and my entities in HA seem to have stopped at the same time.
I'm not sure if this is API related. My API account is still showing daily requests increase but HA data is static .

Anyone else having issues.
From log connection looks ok

Starting GET call against https://api.volvocars.com/connected-vehicle/v2/vehicles/{0}/diagnostics
Nov 01 09:31:40 volvo2mqtt [106] - DEBUG: Response status code: 200
Nov 01 09:31:40 volvo2mqtt [106] - DEBUG: {
  "status" : 200,
  "operationId" : "9268d634-6cd5-4080-a5d9-dbxxxxxxxx",
  "data" : {
    "engineHoursToService" : {
      "name" : "engineHoursToService",
      "value" : "1162",
      "timestamp" : "2023-11-01T09:22:00Z"
    },
    "kmToService" : {
      "name" : "kmToService",
      "value" : "34103",
      "timestamp" : "2023-11-01T09:22:00Z"
    },
    "monthsToService" : {
      "name" : "monthsToService",
      "value" : "18",
      "timestamp" : "2023-11-01T09:22:00Z"
    },
    "serviceWarningStatus" : {
      "name" : "serviceWarningStatus",
      "value" : "NORMAL",
      "timestamp" : "2023-11-01T09:22:00Z"
    },
    "serviceWarningTrigger" : {
      "name" : "serviceWarningTrigger",
      "value" : "",
      "timestamp" : "2023-11-01T09:22:00Z"
    }
  }
}
Nov 01 09:31:40 volvo2mqtt [106] - INFO: Mqtt update done. Next run in 300 seconds.

**Comment by arti273** [comment]
Something strange is going on for me, it may be related.  Only an issue with one entity that I can see, rather than all in your case.
Most entities are updating in HA, and even doors opening and closing are updated every API call. However, battery SoC has not been updated since 20:06 UTC on October 30th. The HA SoC entity is saying it's updated but remains 60%, even when car is at 37%. The correct SoC is showing in the app.  A charge up to 81% didn't change the HA entity. Maybe it is a data issue with the public API, but I would expect the Volvo app to use the same data.
Debug looks normal. Tried a restart of the add-on, checked API call limits, forced a data refresh.  Nada.

**Comment by amurray81** [comment]
So it was the SOC, remaining mileage and charger status that brought it to my attention, I just assumed everything thing was down

**Comment by arti273** [comment]
You're right. The electric range and charger status haven't been updated. The odometer and distance to service are being updated for me. 
Annoying, as SoC drives my charger automation and so I'll need to revert to the Zappi app.
I have an ICE XC90 that I haven't used since 30th Oct, so the distance to empty entity on that hasn't updated.  I'll go for a drive in that later and see if it is the same issue or just the BEV data.
I can't find any way of accessing support from the Volvo Developer Portal, so we may just have to wait and see if it is fixed.

**Comment by Dielee** [comment]
For me it works again. It looks like they fixed the API, maybe someone can confirm?

**Comment by Unwies** [comment]
For me it is still broken. The battery charge level is not the from my car, but it feels like real data, since it is changing. Same for the range. Odometer looks correct. Just checked: I can open/close the car (fortunately not another ones car ;)

**Comment by Dielee** [comment]
Jep, same for me. It charges now a few minutes, after this, it will be your real value again .... Strange!

**Comment by rubenv** [comment]
Feels like the cars couldn't send any data, and they then started working
through the backlog slowly. All a bit delayed.

**Comment by arti273** [comment]
Working for me again.  Just seemed to come back about 3 hours ago (without further intervention) so I assume it was an API issue.

**Comment by Dielee** [comment]
Closing this issue as fixed by Volvo. Thanks @all for the communication!
