### ISSUE TITLE
Installing plug-in results in error message

### ISSUE THREAD

**Issue by canoben** [Dielee/volvo2mqtt#178]
**Describe the bug**
I can't install the plug-in, the following error message is shown:

`Failed to install add-on
The command /bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 3
`

**Version info**:<br>
I'm using Home Assistant 2024.2.5 in a VM on a Synology NAS.

**Comment by Dielee** [comment]
The error says nothing.. 
Please send me the supervisor log from HA.

**Comment by IJsmuur** [comment]
Hello Dielee, 

I'm also trying to install Volvo2mqtt on my Raspberry Pi 4B with HomeAssisant OS. I'm getting the same error (but code:2 instead of code:3)

_Failed to install add-on
The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2._

The Supervisor log says:

_024-07-25 10:17:26.296 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: 982ee2c4_volvo2mqtt
2024-07-25 10:17:26.405 INFO (MainThread) [supervisor.docker.addon] Starting build for 982ee2c4/aarch64-addon-volvo2mqtt:1.9.4
2024-07-25 10:17:27.892 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-07-25 10:17:38.250 ERROR (MainThread) [supervisor.docker.addon] Can't build 982ee2c4/aarch64-addon-volvo2mqtt:1.9.4: The command '/bin/ash -o pipefail -c apk add --no-cache python3 bash py3-pip' returned a non-zero code: 2
2024-07-25 10:17:38.251 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> bbaa6c3a3c1b

Step 3/15 : RUN apk add --no-cache python3 bash py3-pip


 ---> Running in acc4252a8fc5

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz

fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: temporary error (try again later)

WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: temporary error (try again later)

ERROR: unable to select packages:
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by: world[python3]

 ---> Removed intermediate container acc4252a8fc5_

Can you help me how to solve this issue. I also have install the Volvo2mqtt on my Virtual Machine on my QNAP. That installation went oke and without any problem. 

With kind regards,

Maurice
