### ISSUE TITLE
requesting for the OTA all the time

### ISSUE THREAD

**Issue by silkyclouds** [Dielee/volvo2mqtt#218]
We discussed this topic on the HA forums, and you stated that the issue was fixed as the new version had OTA retention, but it keeps happening on my end, (using watchtower, so using the very latest version of the container all the time) that volvo2mqtt requests for the code. it happened this night, so this morning, I have 249 emails sent to me :) 

<img width="260" alt="image" src="https://github.com/user-attachments/assets/4f10f987-1c69-4b38-b5e0-c9b9f0a8c8f4">

any chance to get this fixed once for all ? 

also, I created a python script to inject the one time code, but is there now an easier option to provide the code ? 

Thanks ! :)

**Comment by parisfox** [comment]
Hi,
Same here. Started today...

**Comment by Dielee** [comment]
So, this isn't fixed, as this isn't an add-on issue at all. If the otp is resend, the auth process isn't complete and the addon restarts after a few seconds of waiting. Please provide debug logs from Volvo2mqtt and your supervisor.

**Comment by parisfox** [comment]
I deleted the image entities and it stopped sending new otp since last Sunday. Now I use static pictures of my car and is just fine.

![Volvo C40_exterior](https://github.com/user-attachments/assets/4a12bfa3-4c14-4cac-abaa-8da1d8f07a6c)
![Volvo-C40-Recharge-2023](https://github.com/user-attachments/assets/3fd1a9b1-fc3c-46cd-b894-a0c051b1aa20)
