### ISSUE TITLE
adding Start/stop charging control

### ISSUE THREAD

**Issue by JSCHWAB5** [Dielee/volvo2mqtt#271]
Is it possible to add charging controls ?
In the Volvo App a schedule is availible that can be uses for this purpose.
By editing this (active/inactive) would give some control

for example : schedule from 00:00 to 00:05 for charging. 
Enable the schedule will stop charging (except from 00:00 to 00:05). 
Disable the schedule will start charging

**Comment by htuomola** [comment]
This would be a very nice addition. But maybe it's missing because it is not available in Energy API https://developer.volvocars.com/apis/energy/v1/overview/? Maybe the App uses some private API.

ps. Maybe bot could close inactive issues with some other reason than "completed" as that's kinda misleading.
